### ISSUE TITLE
Very poor documentation. (-5 stars)

### ISSUE THREAD

**Issue by shahidbits** [RatelHub/rflutter_alert#39]
The package is really waste of time. There is no helpful documentation. This package is simply wasytage of time and efforts.

**Comment by cwe1ss** [comment]
Very poor issue (- 5 stars)

The issue is really waste of time. There is no helpful content in this issue. This issue is simply wasytage of time and efforts.

PS: I'm not involved in this project but comments like yours really frustrate OSS authors who put their free time and heart into projects like this so that others can benefit from it without having to pay anything for it.

**Comment by ibrahimdevs** [comment]
@cwe1ss thank you very much for your response and empathy. We have no time for this project lately, but we will improve it soon. And we always appreciate to extra help.
