### ISSUE TITLE
QUESTION: Is there a way to know if an alert is showing?

### ISSUE THREAD

**Issue by evanblasband** [RatelHub/rflutter_alert#80]
I am curious if there is a way to detect if an alert is showing? Like an `isShowing()` method or something? I currently display an alert when a bluetooth device connects but I want to check to see if any alerts are already showing and dismiss them before displaying it.  Any ideas are much appreciated

**Comment by ibrahimdevs** [comment]
@evanblasband I think this issue is not related our plugin. It is much more flutter and coding question which you should ask it on [stackoverflow](https://stackoverflow.com/).

I don't know your navigation structure but if you use rootNavigation, maybe you can call
`Navigator.of(context, rootNavigator: useRootNavigator).pop();`
before you display bluetooth device connection alert. So you can display initial screen without any alerts.
